### ISSUE TITLE
Namespace not specified

### ISSUE THREAD

**Issue by ASKabanets** [dj-yacine-flutter/android_x_storage#3] opened 2024-11-15 21:18 UTC
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':android_x_storage'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file: /Users/john.doe/.pub-cache/hosted/pub.dev/android_x_storage-1.0.0/android/build.gradle. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

     If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.


```

**Comment by djeddi-yacine** [comment] 2024-11-15 21:22
I think this is caused by the new android studio update (ladybug),
I will try to fix it ☺️

**Comment by djeddi-yacine** [comment] 2024-11-15 22:46
the problem was fixed now, if it's still not working consider to reopen the issue.

**Closed as completed by djeddi-yacine** 2024-11-15 22:46 UTC
